### ISSUE TITLE
Registration for DataMobilize Hackathon

### ISSUE THREAD

**Issue by letlabs-ndj** [Kody-SAS/DataMobilize#18]
### Full Name

Ndjesse Letere Emmanuel

### Telephone number

+237 6 56 70 45 10

### Email address

ndjesseletereemmaandy@gmail.com

### Age

Between 18 and 35 years

### Gender

Male

### Nationality

Cameroonian

### Region

Centre

### YOURS REGISTRATION

No

### DataMobilize follower

No

### Coding knowledge

Good

### Road safety knowledge

Moderate

### Telegram handle

Ndjesse Emma

### Team's name

Lameute

### Repository's link

https://github.com/Lameute-Org/lameute-road-safety

### Members in the team

4

### Number of males

3

### Number of females

1

### Criteria satisfaction

Yes

### Project

Road infrastructure defect reporting

### Motivation

We believe that young people have a crucial role to play in shaping the future of road safety. By joining the Global Youth Coalition for Road Safety, we aim to:   Amplify Youth Voices by Collaborating with other young leaders to advocate for policies and initiatives that prioritize road safety ; Drive Innovation through innovative solutions to address road safety challenges

**Comment by letlabs-ndj** [comment]
Registered

**Comment by monkeyK1n9** [comment]
Refer to you team members to have the telegram group invitation link.
