### ISSUE TITLE
Registration for DataMobilize Hackathon

### ISSUE THREAD

**Issue by letlabs-ndj** [Kody-SAS/DataMobilize#19]
### Full Name

Ndjesse Letere Emmanuel

### Telephone number

+237 6 56 70 45 10

### Email address

letlabs.ndj@gmail.com

### Age

Between 18 and 35 years

### Gender

Male

### Nationality

Cameroonian

### Region

Centre

### YOURS REGISTRATION

No

### DataMobilize follower

No

### Coding knowledge

Good

### Road safety knowledge

Moderate

### Telegram handle

Ndjesse Emma

### Team's name

Lameute

### Repository's link

https://github.com/Lameute-Org/lameute-road-safety

### Members in the team

4

### Number of males

3

### Number of females

1

### Criteria satisfaction

Yes

### Project

Road infrastructure defect reporting

### Motivation

We believe that young people have a crucial role to play in shaping the future of road safety.

**Comment by monkeyK1n9** [comment]
This team and project are already participating in the hackathon, I won't accept this participation.
Refer to you team members to have the telegram group invitation link.
